export enum MaintenanceType {
  ROUTINE_CHECK = 'ROUTINE_CHECK',
  BATTERY_REPLACEMENT = 'BATTERY_REPLACEMENT',
  MOTOR_REPAIR = 'MOTOR_REPAIR',
  FIRMWARE_UPDATE = 'FIRMWARE_UPDATE',
  FULL_OVERHAUL = 'FULL_OVERHAUL',
}